### PR TITLE
Flash was shutdown. So I fixed it up.

### PR DESCRIPTION
**Pull request by 3kh0**
I have a website that has unblocked games that do not require flash. I will be forever unblocked.

Please merge this you will not regret it! :)

### CODE REVIEW

**Comment by Vexify4** [comment]
This looks great :) this started out as a for-fun project thank you! I will merge

**Comment by 3kh0** [comment]
Ok thank you!

**Comment by 3kh0** [comment]
You can share my website with your friends

**Comment by Vexify4** [comment]
I will, but I have been learning CSS Do you want me to help with that? On your website?

**Comment by 3kh0** [comment]
> I will, but I have been learning CSS Do you want me to help with that? On your website?

Sure! You can make a pull. I want to make special containers for the ads.

**Comment by Vexify4** [comment]
I'm at school right now but when I get back I will start working on it.

**Comment by 3kh0** [comment]
> I'm at school right now but when I get back I will start working on it.
Ok got it

**Pull request merged**
